package main

// Generated by "go run gentmpl.go form success".
// Do not edit manually.

import (
	"html/template"
)

var formTpl = template.Must(template.New("form").Parse(`<!DOCTYPE html>
<html>
  <head>
    <title>RobustIRC CAPTCHA</title>
	<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400">
	<style type="text/css">
body {
	font-family: "Open Sans";
}

#content {
	text-align: center;
}

#content > * {
	margin-left:auto;
	margin-right:auto
}
	</style>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
	<script type="text/javascript">
function onload() {
	document.getElementById('challenge').value = window.location.hash.substr(1);
}

function solved() {
	document.getElementById('form').submit();
}
	</script>
  </head>
  <body onload="onload()">
    <noscript>
      <p>You need to enable JavaScript for this page.</p>
    </noscript>
    {{ if ne .Msg "" }}
      <p style="text-width: bold">
	  {{ .Msg }}
	  </p>
    {{ end }}
    <div id="content">
	<p>
	Sorry for the inconvenience!
	</p>
	<p>
	In order to protect our IRC network from spammers,<br>
	solving a CAPTCHA is currently required to log in.
	</p>
	<p>
	Please solve the following CAPTCHA:
	</p>
    <form action="/submit" method="POST" id="form" style="width: 304px">
	  <input type="hidden" name="challenge" id="challenge">
      <div class="g-recaptcha" data-sitekey="{{ .SiteKey }}" data-callback="solved"></div>
    </form>
	</div>
  </body>
</html>
`))

var successTpl = template.Must(template.New("success").Parse(`<!DOCTYPE html>
<html>
  <head>
    <title>RobustIRC CAPTCHA</title>
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400">
    <style type="text/css">
body {
    font-family: "Open Sans";
}

#content {
    text-align: center;
}

#content > * {
    margin-left:auto;
    margin-right:auto
}
    </style>
  </head>
  <body onload="onload()">
    <div id="content">
    <p>
    Thanks for your patience!
    </p>
    <p>
    Please proceed with the following command in your IRC client:
    </p>
    <pre>
      {{- if eq (index .Purposeparts 0) "join" -}}
/join {{ index .Purposeparts 2 }} {{ .Token }}
      {{- else if eq (index .Purposeparts 0) "login" -}}
/quote pass captcha={{ .Token }}</pre>
<p>
or:
</p>
<pre>/raw pass captcha={{ .Token }}
      {{- end -}}
    </pre>
    </div>
  </body>
</html>
`))
